-- AlterTable
ALTER TABLE "Store" ADD COLUMN "showDashboardPage" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Store" ADD COLUMN "showLocationsPage" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Store" ADD COLUMN "showUsersPage" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Store" ADD COLUMN "showOrdersPage" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Store" ADD COLUMN "showQuickOrderPage" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Store" ADD COLUMN "showWishlistsPage" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Store" ADD COLUMN "showCreditManagementPage" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Store" ADD COLUMN "showNotificationsPage" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Store" ADD COLUMN "showReportsPage" BOOLEAN NOT NULL DEFAULT true;
