name: Deploy SmartB2B

on:
  push:
    branches: [main]

env:
  VPS_APP_PATH: "/var/www/html/B2b-portal-Public"
  PM2_PROCESS_NAME: "b2b-portal-public"
  NODE_PORT: "3100"

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Sync Code
        run: |
          if [ -d "${{ env.VPS_APP_PATH }}/.git" ]; then
              cd "${{ env.VPS_APP_PATH }}"
              git fetch origin
              git reset --hard "origin/main"
              git clean -fd
          else
              git clone -b main git@github.com:BhavikPatel-dreamz/B2b-portal-Public.git "${{ env.VPS_APP_PATH }}"
          fi

      - name: Build
        run: |
          cd "${{ env.VPS_APP_PATH }}"
          npm install
          npm run build
          
      - name: Copy embed.js to public folder
        run: |
          cp "${{ env.VPS_APP_PATH }}/../B2B-Portal-Front/dist/embe*" \
             "${{ env.VPS_APP_PATH }}/public/."
             
      - name: Start App
        run: |
          cd "${{ env.VPS_APP_PATH }}"
          if pm2 list | grep -q "${{ env.PM2_PROCESS_NAME }}"; then
              pm2 restart "${{ env.PM2_PROCESS_NAME }}"
          else
              PORT=${{ env.NODE_PORT }} pm2 start npm --name "${{ env.PM2_PROCESS_NAME }}" -- start
          fi
          pm2 save
